### ISSUE TITLE
Website nav Home breaks in IPFS gateway

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/hypha.coop#147]
This bug occurs when viewing the website from IPFS gateways (e.g. https://ipfs.distributed.press/ipns/hypha.coop/people/) because of the absolute link here in the menu that takes us to `/`, which in this case becomes the root of the gateway:

<img width="1000" alt="Screen Shot 2022-09-30 at 11 21 40 PM" src="https://user-images.githubusercontent.com/2261308/193385643-e7d26d97-fca6-48a7-a090-feb5e8b71290.png">

To reproduce, go to above link and click `Home` or the top left logo.

The fix would probably be https://github.com/hyphacoop/hypha.coop/blob/master/_includes/sections/navigation.html#L11 but I'll leave this to someone more familiar with the code base.

**Comment by tripledoublev** [comment]
Hi @benhylau,

I wasn't able to replicate this bug. On my end, the Home button worked as expected when viewed from IPFS gateways. 
i.e. Home button links to https://ipfs.distributed.press/ipns/hypha.coop/

Could you give me more contextual information such as the web browser that was used when the bug was discovered?

Thanks!

**Comment by benhylau** [comment]
Seems someone fixed it!

<img width="932" alt="Screen Shot 2022-11-10 at 3 51 57 PM" src="https://user-images.githubusercontent.com/2261308/201203338-3fbdcfb7-3fbf-47de-b25c-7e7357486cc4.png">

Close?

**Comment by tripledoublev** [comment]
Closed!
Thank you!
