### ISSUE TITLE
Transfer ownership of All-Hands calendar invite

### ISSUE THREAD

**Issue by rkashe** [hyphacoop/hypha.coop#203]
Denise and I will be working on All-Hands together. Lexa, can you transfer this calendar invite to me?

Also, Can you review the people included on the everyone@hypha.coop email? I think there are people who should be removed.

**Comment by LexaMichaelides** [comment]
Event transferred. 

everyone@ should include all our members and contractors. Jacky is a current contractor; people like Sacha and Hank are part of 'everyone' because someone in the org thinks they're friendly enough to us that they might work with us again and so we are maintaining their emails (afaik). 

Ivan will be removed when infra deprecates his email, I believe!
